---

- name: Check if GitKraken is already installed
  stat:
    path: /usr/bin/gitkraken
  register: r_gitkraken_check_installed

- name: Install GitKraken
  dnf:
    name: https://release.axocdn.com/linux/gitkraken-amd64.rpm
    disable_gpg_check: yes
    state: present
  become: yes
  when: not r_gitkraken_check_installed.stat.exists
